// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TempleTours.Models;

namespace TempleTours.Migrations
{
    [DbContext(typeof(TempleTourContext))]
    [Migration("20210319040848_Start")]
    partial class Start
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("TempleTours.Models.Group", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupSlotTimeslotID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupID");

                    b.HasIndex("GroupSlotTimeslotID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("TempleTours.Models.TimeslotModel+Timeslot", b =>
                {
                    b.Property<int>("TimeslotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Day")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("TimeslotID");

                    b.ToTable("Timeslot");
                });

            modelBuilder.Entity("TempleTours.Models.Group", b =>
                {
                    b.HasOne("TempleTours.Models.TimeslotModel+Timeslot", "GroupSlot")
                        .WithMany()
                        .HasForeignKey("GroupSlotTimeslotID");

                    b.Navigation("GroupSlot");
                });
#pragma warning restore 612, 618
        }
    }
}
